### ISSUE TITLE
 Question about Future Forecasts

### ISSUE THREAD

**Issue by nick-paduchowski** [jagoosw/gfspy#1]
While trying to query future forecasts, I encounter an error. I do not understand where else I could manipulate the variable or date time to get a value for a future date other than in the get request. I tried to go to the discussions as referenced in the documentation but encountered a 404 not found. I cannot find anything in the documentation that explains how to achieve this. Attached below is the error encountered. Any help would be greatly appreciated! Thank you.

![image](https://user-images.githubusercontent.com/82173102/155441928-1ecc970f-d337-4c61-a6c6-b0df337584e9.png)

**Comment by jagoosw** [comment]
Hi, sorry for the slow reply, not looked at this for a while. When I try this I also get an error, have you managed to make any requests successfully?

**Comment by jagoosw** [comment]
Okay having had a look I think this is an issue with how it selects which forecast to download future data from, for example when I try a request now (13:15), for some future time it is attempting to query the 12:00 model run which isn't available yet (confirmed from looking at the listing [here](https://nomads.ncep.noaa.gov/dods/gfs_0p25/gfs20220302). It is this function: https://github.com/jagoosw/getgfs/blob/1d598ff27ca99af337eb8ad43befdda984cef045/build/lib/gfspy/gfspy.py#L151-L192 When I have time later I will add a check at the end where it queries if the forecast is available yet if the latest forecast time is being requested, and if not step back a model run.

**Comment by jagoosw** [comment]
Now fixed, will be available in next release
