### ISSUE TITLE
Documentation: Longitude is [0,360] and doesn't accept [-180,+180]

### ISSUE THREAD

**Issue by mborrus** [jagoosw/gfspy#3]
This is just a note on documentation you might want to add somewhere as it tripped me up. I'm used to working with longitude on a -180:180 basis. If you put in a negative longitude, the program doesn't throw any issues, it just sets it to zero. I didn't realize this until I had a different, forward looking issue, and I noticed the longitude was off. 

It could be helpful to note this somewhere in the docs, and maybe plug the simple solution that the conversion can be [found using the modulo](https://stackoverflow.com/questions/31820597/map-degrees-to-0-360-in-python), as seen at the bottom of the screenshot.

-100 Longitude == 100W == -100 % 360 == 260; Doesn't break for positive values. (10 % 360 = 10E still)

![Example of longitude difference](https://user-images.githubusercontent.com/38109796/167941287-0f67c049-f28f-485f-ba1a-dbb84f854ebe.png)

**Comment by jagoosw** [comment]
Thanks for bringing this to my attention! I've got a couple of issues to update so hopefully will do this in the next couple of days

**Comment by jagoosw** [comment]
Adding solution to next version!
