### ISSUE TITLE
readthecods todos `Add historical forecasts`

### ISSUE THREAD

**Issue by NicolasMICAUX** [jagoosw/gfspy#4]
In the readthecods todos (https://getgfs.readthedocs.io/en/latest/#todo), you put `Add historical forecasts from https://www.ncei.noaa.gov/thredds/dodsC/model-gfs-004-files-old/202003/20200328/gfs_4_20200328_1800_384.grb2.das`

Are you still on this? Because I'm very interested by this functionnality.

Thx,
N.M.

**Comment by jagoosw** [comment]
I've not had time to work on this for a while so its not really in the works. I don't think it would be that much effort to add it given the existing functionality though, I think you would just need to find the correct urls etc.

Apologies, if I do get onto this I'll update you.

**Comment by NicolasMICAUX** [comment]
No problem.
i found a solution on my side.
Thx a lot for your answer
